FROM openjdk:17-jdk-slim
WORKDIR /app
ARG CODEARTIFACT_AUTH_TOKEN
COPY . /app
RUN ./gradlew :batch:bootJar -PcodeArtifactAuthToken=$CODEARTIFACT_AUTH_TOKEN
ENTRYPOINT java $JAVA_OPTS -jar batch/build/libs/snu4t-batch.jar --job.name=${JOB_NAMES}
