version: "2"
services:
  redis-server:
    container_name: redis-server
    restart: always
    image: "redis"
  node-app:
    container_name: snutt-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12000:12000"
