spring.profiles.active: test

snutt:
  secret-key: test-secret-key

logging:
  level:
    com.mongodb: ERROR

google:
  firebase:
    project-id:
    service-account:
    api-key:
    dynamic-link:
      domain-uri-prefix:
      link-prefix: "https://snutt.page.link"
      android:
        package-name:
      ios:
        bundle-id:
        app-store-id:

http:
  responseTimeout: 3s
