# Build stage
FROM container-registry.oracle.com/graalvm/native-image:25 AS builder
WORKDIR /app
COPY . /app
RUN --mount=type=secret,id=codeartifact_token ./gradlew :batch:nativeCompile -PcodeArtifactAuthToken=$(cat /run/secrets/codeartifact_token)

# Runtime stage
FROM docker.io/debian:stable-slim
WORKDIR /app
COPY --from=builder /app/batch/build/native/nativeCompile/batch /app/batch
ENTRYPOINT ["/app/batch", "--job.name=${JOB_NAME}"]
