# Build stage
FROM container-registry.oracle.com/graalvm/native-image:25 AS builder
WORKDIR /app
COPY . /app
RUN ./gradlew :batch:nativeCompile -PcodeArtifactAuthToken=$(cat /run/secrets/codeartifact_token)

# Runtime stage
FROM docker.io/debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/api/build/native/nativeCompile/batch /app/batch
EXPOSE 8080
ENTRYPOINT ["/app/batch", "--job.name=${JOB_NAME}"]
