# Build stage
FROM container-registry.oracle.com/graalvm/native-image:25-muslib AS builder
WORKDIR /app
ARG CODEARTIFACT_AUTH_TOKEN
COPY . /app
RUN ./gradlew :api:nativeCompile -PcodeArtifactAuthToken=$CODEARTIFACT_AUTH_TOKEN

# Runtime stage
FROM scratch
WORKDIR /app
COPY --from=builder /app/api/build/native/nativeCompile/api /app/api
EXPOSE 8080
ENTRYPOINT ["/app/api"]
