name: deploy-template

on:
  workflow_call:
    inputs:
      ocir_repository:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
        description: 'Dockerfile path (e.g., api/Dockerfile)'
    secrets:
      OCI_CLI_KEY_CONTENT:
        required: true
      OCI_AUTH_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04-arm

    env:
      IMAGE_TAG: ${{ github.run_number }}
      BUILD_NUMBER: ${{ github.run_number }}
      OCIR_REGISTRY: yny.ocir.io
      OCIR_REPOSITORY: ${{ inputs.ocir_repository }}
      OCI_CLI_USER: ocid1.user.oc1..aaaaaaaafispxlhint36zqi2zsobz2svs7egdadtzezmpax3hsumz5ogpnma
      OCI_CLI_TENANCY: ocid1.tenancy.oc1..aaaaaaaajzflhdho73h4er3roso57ebq4jpwt7n5uxg7rrgdnzmjtyeaogxa
      OCI_CLI_FINGERPRINT: "84:0b:80:25:cd:8e:77:b3:77:e5:f5:0f:59:9d:aa:26"
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ap-chuncheon-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to OCIR
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Docker build, tag, and push image to OCIR
        id: build-push-image
        run: |
          echo "${{ github.token }}" > .github_token
          docker build \
            --secret id=github_token,src=./.github_token \
            -f ${{ inputs.dockerfile }} \
            -t $OCIR_REGISTRY/$OCIR_REPOSITORY:$IMAGE_TAG \
            . \
            --platform linux/arm64
          rm -f .github_token
          docker push $OCIR_REGISTRY/$OCIR_REPOSITORY:$IMAGE_TAG
          echo "image=$OCIR_REGISTRY/$OCIR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
