name: Deploy-batch-dev-native

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-native.yml
    with:
      ocir_repository: snutt-dev/snutt-timetable-batch
      dockerfile: batch/Dockerfile-native
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PRIVATE_KEY: ${{ secrets.DEPLOYER_APP_PRIVATE_KEY }}
