name: Deploy-api-prod-native

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-native.yml
    with:
      ocir_repository: snutt-prod/snutt-timetable
      dockerfile: api/Dockerfile-native
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PRIVATE_KEY: ${{ secrets.DEPLOYER_APP_PRIVATE_KEY }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notify
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: snutt-timetable
          avatar-url: https://user-images.githubusercontent.com/35535636/103177470-2237cb00-48be-11eb-9211-3ffa567c8ac3.png
          embed-title: NEW RELEASE
          embed-description: Check [Argo CD](https://argocd.wafflestudio.com) for updated environment
