name: Deploy Manual Native

on:
  workflow_dispatch:
    inputs:
      ocir_repository:
        description: 'OCIR 리포지토리 (예: snutt-dev/snutt-timetable)'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile 경로 (예: api/Dockerfile-native)'
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-native.yml
    with:
      ocir_repository: ${{ inputs.ocir_repository }}
      dockerfile: ${{ inputs.dockerfile }}
    secrets:
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
