name: Deploy-batch-prod

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      ocir_repository: snutt-prod/snutt-timetable-batch
      dockerfile: batch/Dockerfile
    secrets:
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
