name: Deploy-api-dev-native

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-native.yml
    with:
      ocir_repository: snutt-dev/snutt-timetable
      dockerfile: api/Dockerfile-native
    secrets:
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
