name: Deploy-batch-prod-native

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-native.yml
    with:
      ocir_repository: snutt-prod/snutt-timetable-batch
      dockerfile: batch/Dockerfile-native
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
