name: Deploy-batch-dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      ocir_repository: snutt-dev/snutt-timetable-batch
      dockerfile: batch/Dockerfile
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
